<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:app="http://schemas.android.com/apk/res-auto"
xmlns:tools="http://schemas.android.com/tools"
android:layout_width="match_parent"
android:layout_height="match_parent"
tools:context="com.example.acer.myapplication.MainActivity">
<ImageView
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:src="@drawable/logo"
    android:id="@+id/logo"
    />
<LinearLayout
    android:layout_width="wrap_content"
    android:layout_height="60dp"
    android:padding="0dp"
    android:layout_centerHorizontal="true"
    android:layout_alignParentBottom="true"
    android:id="@+id/linearbottom"
    >
    <TextView
        android:layout_width="115dp"
        android:layout_height="80dp"
        android:text="Home"
        android:textColor="#000"
        android:fontFamily="@font/hellight"
        android:textSize="23dp"
        android:padding="20dp"
        android:id="@+id/home"
        android:background="#00BFFF"
        />
    <TextView
        android:layout_width="115dp"
        android:layout_height="80dp"
        android:text="Fav list"
        android:textColor="#000"
        android:fontFamily="@font/hellight"
        android:textSize="23dp"
        android:padding="20dp"
        android:layout_marginRight="0dp"
        android:id="@+id/favlist"
        android:background="#00BFFF"
        />
    <TextView
        android:layout_width="115dp"
        android:layout_height="80dp"
        android:text="Voice"
        android:textColor="#000000"
        android:fontFamily="@font/hellight"
        android:textSize="23dp"
        android:padding="20dp"
        android:layout_marginRight="0dp"
        android:id="@+id/voicelist"
        android:background="#00BFFF"
        />
</LinearLayout>

<!-- <fragment
     android:name="com.example.acer.myapplication.ArticleFragment"
     android:id="@+id/article_fragment"
     android:layout_weight="2"
     android:layout_width="match_parent"
     android:layout_height="90dp"
     android:layout_alignParentBottom="true"/>-->
<RelativeLayout
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_above="@+id/linearbottom"
    >

    <ListView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/mainlistlistview"
        android:focusable="false"
        android:focusableInTouchMode="false">

    </ListView>
    <ListView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/favlistlistview">

    </ListView>
    <ListView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/voicelistview"
        >

    </ListView>
    <ScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:id="@+id/r"
        >
        <RelativeLayout
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginLeft="10dp"
            android:layout_marginRight="10dp"
            android:background="#F2F2F2"

            >
            <ImageView
                android:layout_width="match_parent"
                android:layout_height="150dp"
                android:src="@drawable/gre"
                android:layout_marginTop="30dp"
                android:id="@+id/greimage"/>
            <RelativeLayout
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginRight="20dp"
                android:layout_marginLeft="20dp"
                android:layout_marginTop="220dp"
                android:padding="6dp"
                android:background="#ffffff"
                android:id="@+id/r2">
                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:id="@+id/aboutthetest"
                    android:text="About the test"
                    android:textSize="26dp"
                    android:textColor="#000"
                    />
                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:text="The Graduate Record Examination (GRE), created and administered by ETS, is used by thousands of graduate and business schools to make admission and fellowship decisions. Many graduate programs require scores from the GRE General Test as part of a complete application, and some also require or recommend scores from one more more GRE Subject Tests."
                    android:textSize="20dp"
                    android:layout_marginTop="50dp"
                    android:textColor="#8A8A8A"
                    />
                <ImageView
                    android:layout_width="match_parent"
                    android:layout_height="150dp"
                    android:src="@drawable/gre2"
                    android:layout_marginTop="250dp"
                    android:id="@+id/greimage2"/>
                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:text = "There are three GRE sections: Verbal, Quantitative (math), and Analytical Writing. The GRE tests college-level vocabulary and verbal reasoning; basic math concepts in arithmetic, algebra, and geometry; and your writing and analytical skills. Start to finish, the exam will take you 3 hours and 45 minutes to complete."
                    android:textSize="20dp"
                    android:layout_marginTop="420dp"
                    android:textColor="#8A8A8A"
                    />
            </RelativeLayout>
        </RelativeLayout>
    </ScrollView>
</RelativeLayout>

</RelativeLayout>
